services:

  chiro-db:
    container_name: chiro-app-local
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - chiro_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  pgadmin:
    image: dpage/pgadmin4
    container_name: chiro-pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - chiro-db

  chiro-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chiro-backend
    ports:
      - "3131:3131"
    env_file:
      - .env
    environment:
      NODE_ENV: local
      PORT: 3131
      LOCAL_DB_HOST: chiro-db
      LOCAL_DB_PORT: 5432
      LOCAL_DB_USER: ${POSTGRES_USER}
      LOCAL_DB_PASSWORD: ${POSTGRES_PASSWORD}
      LOCAL_DB_NAME: ${POSTGRES_DB}
    command: npm run start
    depends_on:
      - chiro-db

  frontend:
    image: node:18
    container_name: chiro-frontend
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - chiro-backend

volumes:
  chiro_postgres_data:
  frontend_node_modules:
